version: '3.8'

services:

  fastapi_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      MODEL_URI: ${MODEL_URI}
      MLFLOW_TRACKING_URI: http://127.0.0.1:5000
    env_file:
      - .env
    volumes:
      - ./mlruns:/code/mlruns
    restart: on-failure