stages:
  ingest:
    cmd: python src/data.py
    deps:
      - data/raw/train.csv
      - src/data.py
    outs:
      - data/processed/clean_data.csv

  featurize:
    cmd: python src/features.py
    deps:
      - data/processed/clean_data.csv
      - src/features.py
    outs:
      - data/processed/train_features.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/train_features.csv
      - src/train.py